"""update

Revision ID: 920ce68ed39f
Revises: 76c3fa872df3
Create Date: 2024-09-05 14:13:28.467723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920ce68ed39f'
down_revision = '76c3fa872df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
