"""demo

Revision ID: dd4ed786a211
Revises: 
Create Date: 2024-09-05 13:22:35.890350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4ed786a211'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True, comment='用户名'),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userinfo_id'), 'userinfo', ['id'], unique=False)
    op.create_index(op.f('ix_userinfo_name'), 'userinfo', ['name'], unique=True)
    op.create_index(op.f('ix_userinfo_phone'), 'userinfo', ['phone'], unique=True)
    op.create_index(op.f('ix_userinfo_username'), 'userinfo', ['username'], unique=True)
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('name', sa.TEXT(), nullable=True)
    )
    op.drop_index(op.f('ix_userinfo_username'), table_name='userinfo')
    op.drop_index(op.f('ix_userinfo_phone'), table_name='userinfo')
    op.drop_index(op.f('ix_userinfo_name'), table_name='userinfo')
    op.drop_index(op.f('ix_userinfo_id'), table_name='userinfo')
    op.drop_table('userinfo')
    # ### end Alembic commands ###
